/** @type {import('tailwindcss').Config} */
// Ported from the original inline Stitch config so the compiled stylesheet
// reproduces the "Paper & Grid" design system exactly. See DESIGN.md.
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#444748",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container": "#e9ebe9",
        "secondary-fixed": "#d5e7d6",
        "secondary": "#1f6f4f",
        "on-primary-fixed-variant": "#474746",
        "on-error-container": "#93000a",
        "surface-dim": "#d6dad6",
        "tertiary-fixed": "#d8e6d9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "primary-container": "#222222",
        "surface-container-high": "#e4e7e4",
        "surface-container-low": "#eef0ee",
        "outline-variant": "#c9cec9",
        "primary": "#0b0c0c",
        "on-secondary-container": "#566759",
        "surface-container-highest": "#dde1dd",
        "on-tertiary-container": "#7f8d81",
        "surface-bright": "#f8f9f8",
        "outline": "#6e746e",
        "on-secondary": "#ffffff",
        "secondary-container": "#d2e4d4",
        "on-background": "#1b1c1a",
        "on-tertiary-fixed-variant": "#3d4a40",
        "on-secondary-fixed-variant": "#3b4b3e",
        "inverse-primary": "#c8c6c5",
        "surface-variant": "#dde1dd",
        "inverse-on-surface": "#f2f0ec",
        "on-error": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "inverse-surface": "#30312e",
        "tertiary": "#040e07",
        "background": "#f4f5f4",
        "tertiary-fixed-dim": "#bccabd",
        "on-tertiary-fixed": "#121e16",
        "tertiary-container": "#19251c",
        "on-surface": "#1b1c1a",
        "on-primary": "#ffffff",
        "on-primary-container": "#8a8989",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1b1c1c",
        "surface-tint": "#5f5e5e",
        "secondary-fixed-dim": "#b9cbbb",
        "on-secondary-fixed": "#101f15",
        "surface": "#f4f5f4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "border-thin": "1px",
        "unit": "8px",
      },
      fontFamily: {
        // Instrument-grade grotesk system. Bricolage carries display voice,
        // Archivo does the reading, JetBrains Mono is the data/notation register.
        "headline-lg-mobile": ["Bricolage Grotesque", "sans-serif"],
        "headline-md": ["Bricolage Grotesque", "sans-serif"],
        "caption": ["Archivo", "sans-serif"],
        "label-caps": ["JetBrains Mono", "ui-monospace", "monospace"],
        "headline-lg": ["Bricolage Grotesque", "sans-serif"],
        "body-lg": ["Archivo", "sans-serif"],
        "display": ["Bricolage Grotesque", "sans-serif"],
        "body-md": ["Archivo", "sans-serif"],
        "mono": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        "headline-lg-mobile": ["34px", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-md": ["27px", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "600" }],
        "caption": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "1.0", letterSpacing: "0.14em", fontWeight: "500" }],
        "headline-lg": ["46px", { lineHeight: "1.03", letterSpacing: "-0.035em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.65", fontWeight: "400" }],
        "display": ["82px", { lineHeight: "0.95", letterSpacing: "-0.045em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.65", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
