/** @type {import('tailwindcss').Config} */
// Ported from the original inline Stitch config so the compiled stylesheet
// reproduces the "Paper & Grid" design system exactly. See DESIGN.md.
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#444748",
        "primary-fixed-dim": "#c8c6c5",
        "surface-container": "#efeeea",
        "secondary-fixed": "#d5e7d6",
        "secondary": "#526255",
        "on-primary-fixed-variant": "#474746",
        "on-error-container": "#93000a",
        "surface-dim": "#dbdad6",
        "tertiary-fixed": "#d8e6d9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "primary-container": "#222222",
        "surface-container-high": "#eae8e4",
        "surface-container-low": "#f5f3ef",
        "outline-variant": "#c4c7c7",
        "primary": "#0b0c0c",
        "on-secondary-container": "#566759",
        "surface-container-highest": "#e4e2de",
        "on-tertiary-container": "#7f8d81",
        "surface-bright": "#fbf9f5",
        "outline": "#747878",
        "on-secondary": "#ffffff",
        "secondary-container": "#d2e4d4",
        "on-background": "#1b1c1a",
        "on-tertiary-fixed-variant": "#3d4a40",
        "on-secondary-fixed-variant": "#3b4b3e",
        "inverse-primary": "#c8c6c5",
        "surface-variant": "#e4e2de",
        "inverse-on-surface": "#f2f0ec",
        "on-error": "#ffffff",
        "primary-fixed": "#e5e2e1",
        "inverse-surface": "#30312e",
        "tertiary": "#040e07",
        "background": "#fbf9f5",
        "tertiary-fixed-dim": "#bccabd",
        "on-tertiary-fixed": "#121e16",
        "tertiary-container": "#19251c",
        "on-surface": "#1b1c1a",
        "on-primary": "#ffffff",
        "on-primary-container": "#8a8989",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1b1c1c",
        "surface-tint": "#5f5e5e",
        "secondary-fixed-dim": "#b9cbbb",
        "on-secondary-fixed": "#101f15",
        "surface": "#fbf9f5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "64px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "border-thin": "1px",
        "unit": "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["EB Garamond", "serif"],
        "headline-md": ["EB Garamond", "serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["EB Garamond", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "400" }],
        "caption": ["13px", { lineHeight: "1.4", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
